// Fill out your copyright notice in the Description page of Project Settings.


#include "BeatUnit/Obstacles.h"
#include "PlayerCharacter.h"
#include "GameFramework/Character.h"
#include "Components/StaticMeshComponent.h"
#include "Components/BoxComponent.h"
#include <Kismet/GameplayStatics.h>
#include "UObject/ConstructorHelpers.h"

AObstacles::AObstacles()
{
    PrimaryActorTick.bCanEverTick = true;

    objectMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ObjectMesh"));
    RootComponent = objectMesh;

    BoxCollision = CreateDefaultSubobject<UBoxComponent>(TEXT("BoxComponent"));
    BoxCollision->SetupAttachment(RootComponent);

    BoxCollision->OnComponentBeginOverlap.AddDynamic(this, &AObstacles::OnOverlapBegin);
    BoxCollision->SetCollisionResponseToAllChannels(ECR_Overlap);
}

void AObstacles::BeginPlay()
{
    Super::BeginPlay();

    if (!bCanDealDamage || !auraMaterial) return;
    // ğŸ”¹ ëŒ€ë¯¸ì§€ ì´í™íŠ¸ í™œì„±í™” ì—¬ë¶€ ì„¤ì •
    UMaterialInstanceDynamic* DynamicMaterial = UMaterialInstanceDynamic::Create(auraMaterial, this);
    objectMesh->SetOverlayMaterial(DynamicMaterial);
}

void AObstacles::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
}

void AObstacles::KnockBack(AActor* player)
{
    if (player)
    {
        // ë°©í–¥ ê³„ì‚°
        FVector PushDirection = (player->GetActorLocation() - GetActorLocation()).GetSafeNormal();
        FVector PushForce = PushDirection * 1000.0f; // 1000.0fëŠ” ê°•ë„ ê°’
        PushForce.Z = 0;

        APlayerCharacter* Player = Cast<APlayerCharacter>(player);

        // ë°€ì–´ë‚´ê¸°
        Player->LaunchCharacter(PushForce, true, true);
        Player->Take_HP(-damageAmount, this);
    }
}

void AObstacles::OnOverlapBegin(UPrimitiveComponent* OverlappedComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
    if (!OtherActor || OtherActor == this) return;

    if (OtherActor->ActorHasTag(FName("PurificationTarget"))) return;

    // ì¶©ëŒí•œ ì˜¤ë¸Œì íŠ¸ê°€ í”Œë ˆì´ì–´ì¸ì§€ í™•ì¸
    if (Cast<APlayerCharacter>(OtherActor) && bCanDealDamage)
    {
        KnockBack(OtherActor);
        return;  // í”Œë ˆì´ì–´ì™€ ì¶©ëŒ ì‹œ ì•„ë¬´ í–‰ë™ë„ í•˜ì§€ ì•ŠìŒ
    }
}

