// Fill out your copyright notice in the Description page of Project Settings.

#include "BeatUnit/Enemy/EnemyBase.h"
#include "BeatUnit/Enemy/EnemyDataTable.h"
#include "BeatUnit/Enemy/EnemyStatComp.h"
#include "BeatUnit/Enemy/Enemy_AIController.h"

#include "Components/CapsuleComponent.h"
#include "Components/WidgetComponent.h"

#include "Kismet/GameplayStatics.h"
#include "GameFramework/Character.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "UObject/ConstructorHelpers.h"
#include "Manager/StageManager.h"
#include "Manager/TutorialManager.h"
#include "NiagaraFunctionLibrary.h"
#include "LevelDesign/Camera_Map.h"
#include "Widget/Widget_EnemyHealthBar.h"
#include "Widget/ActorWidgetInterface.h"
#include <Components/ProgressBar.h>

#define HPBAR_WIDTH 150
#define HPBAR_HEIGHT 15

// Sets default values
AEnemyBase::AEnemyBase()
{
	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	static ConstructorHelpers::FObjectFinder<UDataTable>EnemyDataObject(TEXT("/Script/Engine.DataTable'/Game/Data/EnemyDataTable.EnemyDataTable'"));
	static ConstructorHelpers::FClassFinder<UWidget_EnemyHealthBar> HealthBarWidgetClass(TEXT("/Game/UI/HUD/WBP_EnemyHealthBar"));
	

	HPBarWidget = CreateDefaultSubobject<UWidgetComponent>(TEXT("HPBar"));
	EnemyStatComp = CreateDefaultSubobject<UEnemyStatComp>(TEXT("ENEMYSTAT"));

	//Îç∞Ïù¥ÌÑ∞ ÌÖåÏù¥Î∏îÍ≥º Ïò§Î∏åÏ†ùÌä∏ Ïó∞Í≤∞*
	EnemyDataTable = EnemyDataObject.Object;
	Tags.Add(TEXT("PurificationTarget"));

	GetCapsuleComponent()->InitCapsuleSize(35.0f, 35.0f);

	//Ï≤¥Î†•Î∞î ÏúÑÏ†Ø Ïª¥Ìè¨ÎÑåÌä∏ ÏÜçÏÑ± ÏÑ§Ï†ï
	HPBarWidget->SetupAttachment(RootComponent);
	HPBarWidget->SetWidgetSpace(EWidgetSpace::Screen);
	HPBarWidget->SetDrawSize(FVector2D(HPBAR_WIDTH, HPBAR_HEIGHT));
	HPBarWidget->SetRelativeRotation(FRotator(90.0f, 0.0f, 0.0f));
	HPBarWidget->SetRelativeLocation(FVector(0.0f, 0.0f, 0.0f));
	HPBarWidget->SetWidgetClass(HealthBarWidgetClass.Class);
	HPBarWidget->SetTickWhenOffscreen(true);

	// AI Ïª®Ìä∏Î°§Îü¨ ÌÅ¥ÎûòÏä§, AI ÏûêÎèôÎπôÏùò
	// Ìè∞Ïùò ÏÉùÏÑ± Î∞è AI Ïª®Ìä∏Î°§Îü¨Ïóê ÏùòÌïú ÎπôÏùò ÏãúÍ∏∞Î•º Í≤∞Ï†ï
	// Ìè∞Ïù¥ AIÏóê ÏùòÌï¥ Ïª®Ìä∏Î°§Îê† Îïå Í∏∞Î≥∏ÏúºÎ°ú ÏÇ¨Ïö©Ìï† AI Ïª®Ìä∏Î°§Îü¨ ÌÅ¥ÎûòÏä§
	AIControllerClass = AEnemy_AIController::StaticClass();
	AutoPossessAI = EAutoPossessAI::PlacedInWorldOrSpawned;

	//ÎÇòÏ§ëÏóê Ï†ïÏòàÎ™π ÎÇòÏò§Î©¥ dataTableÏóêÏÑú Í∞íÏùÑ Í∞ÄÏ†∏Ïò§Í≤åÌï†Í≤É
	SetEnemyType(EEnemyType::Common);
}

// Called when the game starts or when spawned
void AEnemyBase::BeginPlay()
{
	Super::BeginPlay();

	CheckGround();
	StageManager = GetStageManager();
	if (StageManager->IsTutorialStage()) {
		TutorialManager = StageManager->GetTutorialManager();
	}

	//DataTable 
	LoadEnemyData();
	InitEnemyData();

	fade_material = UMaterialInstanceDynamic::Create(GetMesh()->GetMaterial(0), this);
	GetMesh()->SetMaterial(0, fade_material);

	//Handler Ï∂îÍ∞Ä
	GetCapsuleComponent()->OnComponentBeginOverlap.AddDynamic(this, &AEnemyBase::OnOverlapBegin);

	/*if (UUserWidget* Widget = HPBarWidget->GetUserWidgetObject())
	{
		// Ï≤¥Î†• Î∞îÏù∏Îî© Î°úÏßÅ Ï∂îÍ∞Ä Í∞ÄÎä•
	}*/

	TArray<AActor*> CameraMaps;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), ACamera_Map::StaticClass(), CameraMaps);

	if (CameraMaps.Num() > 0)
	{
		UnitList_Manager = Cast<ACamera_Map>(CameraMaps[0]);
	}

	FVector2D ViewportSize;
	GEngine->GameViewport->GetViewportSize(ViewportSize);
	HPBarWidget->SetDrawSize(FVector2D(HPBAR_WIDTH * (ViewportSize.X / 1920), HPBAR_HEIGHT * ViewportSize.Y / 1080));
	UWidget_EnemyHealthBar* HPBar = Cast<UWidget_EnemyHealthBar>(HPBarWidget->GetUserWidgetObject());
	if (HPBar)
	{
		HPBar->InitWidget(this);
	}
	else
	{
		LOG_DEBUG(Warning, TEXT("Can't Find HPBar"));
	}
	
}

void AEnemyBase::Tick(float DeltaTime)
{
	//Super::Tick(DeltaTime);

	UpdateHealthBar();
	if(GetIsLiving()&& bLookAtPlayer)	LookAtPlayer();

	if (!GetWorld() || !GetOwner()) return;

	FVector CurrentLocation = GetActorLocation() + FVector(60.f, 0.f, 0.f);

	// Ïπ¥Î©îÎùº ÏúÑÏπò Í∞ÄÏ†∏Ïò§Í∏∞
	FVector CameraLocation = UGameplayStatics::GetPlayerCameraManager(GetWorld(), 0)->GetCameraLocation();
	CameraLocation.X = 0;
	CameraLocation.Y = 0;

	FVector WidgetLocation = GetOwner()->GetActorLocation();
	WidgetLocation.X = 0;
	WidgetLocation.Y = 0;

	// Ïπ¥Î©îÎùºÎ•º Î∞îÎùºÎ≥¥Îäî Î∞©Ìñ• Í≥ÑÏÇ∞
	FVector DirectionToCamera = (CameraLocation - WidgetLocation).GetSafeNormal();

	// ÏúÑÏ†ØÏùò Yaw(ÏàòÌèâ) ÌöåÏ†ÑÎßå Ïú†ÏßÄ
	FRotator LookAtRotation = FRotationMatrix::MakeFromX(DirectionToCamera).Rotator();

	// ÌöåÏ†Ñ ÏÑ§Ï†ï
	HPBarWidget->SetWorldRotation(LookAtRotation);
	HPBarWidget->SetWorldLocation(CurrentLocation);

	if (bIsDashing) {
		if (HasDashFx && DashTimeElapsed <= 0.0001f) { 
			SpawnDashFx(DashFx, DashFxNiagaraComponent, StartLocation, EndLocation, FVector(0.9f, 0.3f, 0.1f), 0.3f); 
		} 
		DashTimeElapsed += DeltaTime; 
		float Alpha = DashTimeElapsed / DashDuration; 
		FVector NewLocation = FMath::Lerp(StartLocation, EndLocation, Alpha); 
		// ÎåÄÏãú Ïù¥Îèô Ï≤òÎ¶¨ //
		FHitResult Hit; GetRootComponent()->MoveComponent(NewLocation - GetActorLocation(), GetActorRotation(), true, &Hit); 
		//Ï∂©Îèå Ïó¨Î∂Ä ÌôïÏù∏ 
		if (Hit.IsValidBlockingHit()) { 
			//ÎåÄÏâ¨ Ïù¥ÌéôÌä∏ Ï§ëÎã® 
			if (DashFxNiagaraComponent != nullptr) {
				DashFxNiagaraComponent->SetVisibility(false); //ÎßâÌòîÏùÑ Ïãú ÎåÄÏâ¨ Ïù¥ÌéôÌä∏ Ï†úÍ±∞ 
			} 
		} // ÎåÄÏãú ÏãúÍ∞Ñ Ï¢ÖÎ£å Ïãú Î©àÏ∂§ 
		if (DashTimeElapsed >= DashDuration) 
		{ 
			bIsDashing = false; DashTimeElapsed = 0.0f;
		} 
	}
}

void AEnemyBase::ActiveUnit()
{
	Super::ActiveUnit();
	if (!GetCharacterMovement()) return;
	GetCharacterMovement()->GravityScale = 1.0f;
	//ÏñòÍ∞Ä ÏûêÍæ∏ ÌîåÎ†àÏù¥ÌïòÎ©¥ ÏïÑÎûòÎ°ú Îñ®Ïñ¥Ï†∏ÏÑú Ï§ëÎ†•ÎßâÏïÑÎÜ®Îã§Í∞Ä Ìë∏Îäî ÏãúÏ†ê
	//Î≤ÑÍ∑∏ ÏïåÏïÑÎÇ¥Î©¥ Î∞îÍæ∏ÏûêÏûá

	UnitList_Manager->RegisterUnit(this, GetBeatIndex(),GetQuaterBeatIndex());
}

// Called to bind functionality to input
void AEnemyBase::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);
}


void AEnemyBase::Charge()
{
	ACharacter* PlayerCharacter = UGameplayStatics::GetPlayerCharacter(GetWorld(), 0);

	CanDash = false;

	if (PlayerCharacter)
	{
		FVector PlayerLocation = PlayerCharacter->GetActorLocation();
		FVector TargetVector = PlayerLocation - GetActorLocation();
		TargetVector.Z = 0.0f;  // ÏàòÏßÅ Î∞©Ìñ• Î¨¥Ïãú

		if (!TargetVector.IsNearlyZero())
		{
			StartLocation = GetActorLocation();
			FVector DashDirection = TargetVector.GetSafeNormal();  // ÎåÄÏãú Î∞©Ìñ• ÏÑ§Ï†ï
			EndLocation = StartLocation + DashDirection * DashDistance;

			bIsDashing = true;
			DashTimeElapsed = 0.0f;
		}
		else
		{
			LOG_KHJ(Error, TEXT("Dash failed: Invalid target vector"));
		}
	}
}

//EnemyDataÏóê ÏûàÎäî DataIndexÌñâÏùò Ï†ïÎ≥¥Î•º Í∞ÄÏ†∏Ïò¥
FEnemyDataStruct* AEnemyBase::GetEnemyData()
{
	//ÎÇòÏ§ëÏóêÎäî DataIndex ÎåÄÏã†Ìï¥ÏÑú Îã§Î•∏ Î∞©ÏãùÏúºÎ°ú Íµ¨ÌòÑÌï† Í≤É, ÏßÅÍ¥ÄÏ†ÅÏù¥ÏßÄ ÏïäÏùå
	if (EnemyType == ECommonEnemyType::None)
	{
		return EnemyDataTable->FindRow<FEnemyDataStruct>(*FString::FromInt(DataIndex), TEXT("EnemyDataTable"));
	}

	TArray<FEnemyDataStruct*> EnemyDataStructs;
	EnemyDataTable->GetAllRows(TEXT("EnemyData"), EnemyDataStructs);

	for (FEnemyDataStruct* EnemyData : EnemyDataStructs)
	{
		if (EnemyData && EnemyData->EnemyType == this->EnemyType)
		{
			return EnemyData;
		}
	}

	LOG_DEBUG(Warning, TEXT("EnemyData can't get"));

	return nullptr;
}


//Í∞ÄÏ†∏Ïò® EnemyDataÎ•º Î°úÏª¨ Î≥ÄÏàòÏóê Ï†ÄÏû•
void AEnemyBase::LoadEnemyData()
{
	FEnemyDataStruct* EnemyData = GetEnemyData();

	if (!EnemyData) return;

	this->ID = EnemyData->D_ID;
	this->EnemyStatData = EnemyData->StatData;
	this->EnemyAssetData = EnemyData->AssetData;
	this->EnemyAbilityData = EnemyData->AbilityData;
}

void AEnemyBase::InitEnemyData()
{
	// --- Ï≤¥Î†• Ï¥àÍ∏∞Ìôî ---
	if (EnemyStatComp)
		EnemyStatComp->InitHealth(EnemyStatData.D_MaxHealth);
	// --- Ïù¥Îèô ÏÜçÎèÑ ---
	if (UCharacterMovementComponent* MoveComp = GetCharacterMovement())
		MoveComp->MaxWalkSpeed = EnemyStatData.D_Speed;

	// --- Î©îÏãú & Î®∏Ìã∞Î¶¨Ïñº ÏÑ∏ÌåÖ ---
	if (EnemyAssetData.SkelMesh)
	{
		GetMesh()->SetSkeletalMesh(EnemyAssetData.SkelMesh);
		GetMesh()->SetRelativeScale3D(SkelMeshSize);
		GetMesh()->SetRelativeLocationAndRotation(MeshLocation, MeshRotation);

		FString AuraPath = TEXT("/Game/Assets/Aura/Enemy_Material_Aura_Red2.Enemy_Material_Aura_Red2");
		UMaterialInterface* Aura = LoadObject<UMaterialInterface>(nullptr, *AuraPath);
		GetMesh()->SetOverlayMaterial(Aura);
	}

	if (EnemyAssetData.Color)
		GetMesh()->SetMaterial(0, EnemyAssetData.Color);


	// --- ÎåÄÎØ∏ÏßÄ Ï≤òÎ¶¨ ÌîåÎûòÍ∑∏ ---
	this->CanTakeNormal = EnemyStatData.TakeDamage_NormalAttack;
	this->CanTakeDash = EnemyStatData.TakeDamage_DashAttack;
	this->ApplyDamageType = EnemyStatData.EnemyApplyDamageType;

	// --- Ïñ¥ÎπåÎ¶¨Ìã∞ ---
	this->HasDashAbility = EnemyAbilityData.bHasDash;
	this->bLookAtPlayer = EnemyAbilityData.bLookAtPlayer;

	if (HasDashAbility)
	{
		const FEnemyDashAbility& DashData = EnemyAbilityData.DashAbility;

		this->DashCount = DashData.D_DashCount;
		this->CurDashCount = 0;
		this->DashDistance = DashData.D_DashDistance;
		this->DashDuration = DashData.D_DashBeat * StageManager->GetBeatPerSecond();
		
		this->HasDashFx = DashData.D_HasDashFx;
		this->DashFx = DashData.D_DashFx;
	}

	// --- HP Bar UI ---
	if (HPBarWidget)
		HPBarWidget->SetVisibility(EnemyAbilityData.bOnHealthBarUI);
	

	// --- ÌöåÏ†Ñ Ï≤òÎ¶¨ ---
	if (UCharacterMovementComponent* MoveComp = GetCharacterMovement())
	{
		if (bLookAtPlayer)
		{
			bUseControllerRotationYaw = true;
			MoveComp->bOrientRotationToMovement = false;
		}
		else
		{
			bUseControllerRotationYaw = false;
			MoveComp->bOrientRotationToMovement = true;
		}
	}
}


void AEnemyBase::BeatUpdate(int QuaterIndex)
{
	if (QuaterIndex != 0 || bIsDashing) return;

	if (DashCount == CurDashCount) {
		CurDashCount = 0;
		Charge();
	}
	else {
		CurDashCount++;
	}
}

void AEnemyBase::OnOverlapBegin(UPrimitiveComponent* OverlappedComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	APlayerCharacter* Player = Cast<APlayerCharacter>(OtherActor);

	if (Player)
	{
		if (OtherComp && OtherComp->ComponentHasTag(TEXT("Sword")))
		{
			return; // Ï∂©Îèå Ïù¥Î≤§Ìä∏ Ï≤òÎ¶¨ Ï¢ÖÎ£å
		}
		else if (OtherComp && OtherComp->ComponentHasTag(TEXT("HitRange"))) {
			//ÌîåÎ†àÏù¥Ïñ¥ Í≥µÍ≤© ÌïòÎäî ÌÉÄÏù¥Î∞ç
			//Ïù¥ÌõÑÏóê Í≥µÍ≤©ÌõÑ Îã§Î•∏ Í∏∞Îä• Íµ¨ÌòÑÏãú Ïó¨Í∏∞Ïóê Ìï†Í≤É
			AttackPlayer(Player);
		}
	}
}

void AEnemyBase::AttackPlayer(APlayerCharacter* Player)
{
	switch (ApplyDamageType)
	{
	case EApplyDamageType::Always:
		Player->Take_HP(-EnemyStatData.D_Damage, this);
		break;
	case EApplyDamageType::OnAttack:
		if(bIsDashing) Player->Take_HP(-EnemyStatData.D_Damage, this);
		break;
	case EApplyDamageType::Never:
		break;
	default:
		break;
	}

}

void AEnemyBase::UpdateHealthBar()
{
	UWidget_EnemyHealthBar* HPBar = Cast<UWidget_EnemyHealthBar>(HPBarWidget->GetUserWidgetObject());
	HPBar->UpdateValue();
}

//ÌîåÎ†àÏù¥Ïñ¥ÏóêÍ≤å ÎßûÎäî Ìï®Ïàò
void AEnemyBase::TakeDamagePlayer(float Damage, EJudgementResult Judgement, AActor* DamageCauser)
{
	LOG_KHJ(Display, TEXT("[Attack Log] Damage: %.1f | Judgement: %d | Causer: %s"),
		Damage,
		static_cast<int32>(Judgement),
		*DamageCauser->GetName()
	);
	HitReaction(Damage, Judgement);
}

void AEnemyBase::MoveOut()
{
	/*
	//xÏ∂ïÍ∏∞Ï§Ä  ÌöåÏ†ÑÌñâÎ†¨ Î≥ÄÌôò
	FRotator NewRotation = FRotationMatrix::MakeFromX(MoveDirection).Rotator();
	//Ïπ¥Î©îÎùº Ïù¥ÎèôÎ∞©Ìñ• Î∞òÎåÄÎ°ú ÌöåÏ†Ñ
	SetActorRotation(NewRotation);
	FVector CurrentLocation = GetActorLocation();  // ÌòÑÏû¨ ÏúÑÏπò
	FVector TargetLocation = CurrentLocation + (MoveDirection * GetCharacterMovement()->MaxWalkSpeed * GetWorld()->GetDeltaSeconds());  // Î™©Ìëú ÏúÑÏπò (Ïù¥Îèô Î∞©Ìñ• * ÏÜçÎèÑ)
	
	// ÏÉàÎ°úÏö¥ ÏúÑÏπòÎ°ú Ïù¥Îèô
	SetActorLocation(TargetLocation);
	*/
	TimeElapsed += 0.016f;

	fade_material->SetScalarParameterValue(FName("opacity"), 1 - TimeElapsed);

	// ÏùºÏ†ï ÏãúÍ∞Ñ ÎèôÏïà Ïù¥Îèô ÌõÑ Î©àÏ∂îÍ≥† Ïú†ÎãõÏùÑ ÎπÑÌôúÏÑ±Ìôî
	if (TimeElapsed > 1.0f)  //1Ï¥àÌõÑ
	{
		GetWorld()->GetTimerManager().ClearTimer(DeathMoveTimer);  // ÌÉÄÏù¥Î®∏ Ï¢ÖÎ£å
		DeactiveUnit();  // Ïú†Îãõ ÎπÑÌôúÏÑ±Ìôî
	}
}
//Î∞ëÏóê Î∞îÎã•Ïù¥ ÏóÜÏúºÎ©¥ killzÏóê Í∞ÄÍ∏∞Ï†ÑÏóê ÏÇ≠Ï†ú
void AEnemyBase::CheckGround()
{
	GetCharacterMovement()->GravityScale = 0.0f;

	FVector Start = GetActorLocation();
	FVector End = Start - FVector(0, 0, 1000); // üîπ ÏïÑÎûò Î∞©Ìñ•ÏúºÎ°ú ÎùºÏù∏Ìä∏Î†àÏù¥Ïä§

	FHitResult HitResult;
	FCollisionQueryParams QueryParams;
	QueryParams.AddIgnoredActor(this); // üîπ ÏûêÍ∏∞ ÏûêÏã† Î¨¥Ïãú

	bool bHit = GetWorld()->LineTraceSingleByChannel(HitResult, Start, End, ECC_Visibility, QueryParams);

	if (!bHit)
	{
		Destroy();
		return;
	}

	FVector TargetLocation = HitResult.ImpactPoint + FVector(0, 0, 10); // Î∞îÎã• ÏúÑ 10 Ïú†Îãõ
	SetActorLocation(TargetLocation);
}

void AEnemyBase::HitReaction(float DamageAmount, EJudgementResult Judgement)
{
	

	SpawnHitFx(Judgement);

	if (Judgement == EJudgementResult::DashPerfect || Judgement == EJudgementResult::AttackPerfect)
	{
		UpdatePlayerRecordOnPerfectHit();
	}

	if (EnemyStatComp->DecreaseHealth(DamageAmount))
	{
		UpdatePlayerRecordOnDied();
		
		//Ïú†Îãõ Ï£ΩÏùåÏ≤òÎ¶¨
		LivingUnit();
		GetMesh()->SetOverlayMaterial(nullptr);
		FTimerHandle PurificationTimerHandle;
		
		if (AController* AIController = GetController())
		{
			AIController->UnPossess();
			//LOG_SGS_SCREEN(3.f, TEXT("%s"), *MoveDirection.ToString());

		}
		//Î©îÏâ¨ÏôÄ Ï∫°Ïäê ÎÖ∏ÏΩúÎ¶¨Ï†ÑÌôî
		GetCapsuleComponent()->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		GetMesh()->SetCollisionEnabled(ECollisionEnabled::NoCollision);

		//Î≤°ÌÑ∞Î∞©Ìñ• Ï†ïÍ∑úÌôî
		//MoveDirection = MoveDirection.GetSafeNormal();
		//1ÌîÑÎ†àÏûÑÎßàÎã§ Ïù¥ÎèôÌïòÎèÑÎ°ù Ìò∏Ï∂ú
		GetWorld()->GetTimerManager().SetTimer(DeathMoveTimer, this, &AEnemyBase::MoveOut, 0.016f, true);
		

		//Ïú†ÎãõÏù¥ Ï£ΩÏùÑ Îïå Ï∂úÎ†•ÌñàÎçò ÎåÄÏâ¨ Ïù¥ÌéôÌä∏ Ï†úÍ±∞
		if (DashFxNiagaraComponent != nullptr)
		{
			DashFxNiagaraComponent->SetVisibility(false);  
		}
		
		//DeactiveUnit(); //on death
	}
}

void AEnemyBase::SpawnHitFx(EJudgementResult Judgement)
{
	//EJudgementResultÎ•º Î≥¥Î©¥ ÎåÄÏãúÏôÄ Í≥µÍ≤©ÏùÑ 10ÏúºÎ°ú Íµ¨Î∂Ñ
	const int JudgeModular = 10;
	int AttackJudge = static_cast<int32>(Judgement);
	int AttackFxNum = AttackJudge % JudgeModular - 1;

	if (AttackFxNum >= 0)	OnEnemyHitFx(AttackFxNum);
}

void AEnemyBase::UpdatePlayerRecordOnPerfectHit()
{
	StageManager->AddCombo(1);
	StageManager->AddScore(StageManager->GetNowCombo() * 100);
}

void AEnemyBase::UpdatePlayerRecordOnDied()
{
	StageManager->AddScore(EScoreType::KillEnemy);
	const int PurificationCount = 1;
	StageManager->IncreasePurificationCount(PurificationCount);
}

AStageManager* AEnemyBase::GetStageManager()
{
	TArray<AActor*> FoundActors;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), AStageManager::StaticClass(), FoundActors);

	if (FoundActors.Num() > 0)
	{
		// Ï≤´ Î≤àÏß∏ StageManagerÎ•º Í∞ÄÏ†∏Ïò¥
		return Cast<AStageManager>(FoundActors[0]);
	}
	LOG_KHJ(Error, TEXT("Ìï¥Îãπ Ïä§ÌÖåÏù¥ÏßÄÏóê stagemanagerÍ∞Ä ÏóÜÏùå"));
	return nullptr;
}

void AEnemyBase::LookAtPlayer()
{
	ACharacter* PlayerCharacter = UGameplayStatics::GetPlayerCharacter(GetWorld(), 0);
	if (!PlayerCharacter) return;

	FVector PlayerLocation = PlayerCharacter->GetActorLocation();
	FVector EnemyLocation = GetActorLocation();

	FVector DirectionToPlayer = (PlayerLocation - EnemyLocation).GetSafeNormal();
	DirectionToPlayer.Z = 0.0f;

	FRotator LookAtRotation = FRotationMatrix::MakeFromX(DirectionToPlayer).Rotator();
	SetActorRotation(LookAtRotation);
}

ECamDirection AEnemyBase::GetCameraDirection()
{
	TArray<AActor*> FoundActors;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), ACamera_Map::StaticClass(), FoundActors);

	if (FoundActors.Num() > 0)
	{
		ACamera_Map* CameraMap = Cast<ACamera_Map>(FoundActors[0]);
		if (CameraMap)
		{
			return CameraMap->GetDirection();
		}
		else
		{
			LOG_KHJ(Error, TEXT("Ïπ¥Î©îÎùºÎßµ Î™ªÏ∞æÏùå"));
		}
	}
	else
	{
		LOG_KHJ(Error, TEXT("Ïπ¥Î©îÎùºÎßµ ÏóÜÏùå"));
	}
	return ECamDirection::Start;
}

void AEnemyBase::OnEnemyHitFx(int index) {
	if (NiagaraSystemAssets.IsValidIndex(index)) {
		UNiagaraFunctionLibrary::SpawnSystemAtLocation(
			GetWorld(),
			NiagaraSystemAssets[index],
			GetActorLocation(),
			GetActorRotation()
		);
	}
	else
	{
		LOG_DEBUG(Error, TEXT("Hit Fx didn't included"));
	}
}

//AttackTypeÏóê Îî∞Îùº Îç∞ÎØ∏ÏßÄÎ•º Î∞õÎäîÏßÄ ÏïàÎ∞õÎäîÏßÄÎ•º Î¶¨ÌÑ¥ Ìï¥Ï§å
bool AEnemyBase::IsAvailableForAttack(EAttackType AttackType)
{
	if (AttackType == EAttackType::Normal) {
		return EnemyStatData.TakeDamage_NormalAttack;
	}
	else if (AttackType == EAttackType::Dash) {
		return EnemyStatData.TakeDamage_DashAttack;
	}
	else
	{
		LOG_KHJ(Error, TEXT("ÎßûÏßÄÏïäÎäî Îç∞ÎØ∏ÏßÄ ÌÉÄÏûÖ"));
		return false;
	}

}

bool AEnemyBase::IsInView() {
	return bInView;
}

void AEnemyBase::SetbInView(bool bIsInView)
{
	this->bInView = bIsInView;
}

void AEnemyBase::SetCommonEnemyType(ECommonEnemyType NewEnemyType)
{
	EnemyType = NewEnemyType;
}

void AEnemyBase::SpawnDashFx(UNiagaraSystem* Fx, UNiagaraComponent*& NiagaraComponent, const FVector& StartVector, const FVector& EndVector, FVector FxScaleMultiplier, float EffectLocationAlpha)
{
	if (Fx)
	{
		// ÎåÄÏãú Î∞©Ìñ• Í≥ÑÏÇ∞
		FVector DashDirection = (EndVector - StartVector).GetSafeNormal(); // ÎåÄÏâ¨ Î∞©Ìñ•ÏùÑ Ï†ïÍ∑úÌôî Î≤°ÌÑ∞Î°ú Î≥ÄÌôò
		FRotator DashRotation = DashDirection.Rotation(); // Ï†ïÍ∑úÌôî Î≤°ÌÑ∞Î°ú ÌöåÏ†ÑÍ∞í Í≥ÑÏÇ∞
		// Ïù¥ÌéôÌä∏Ïùò ÏúÑÏπò Ï°∞Ï†ï (ÏãúÏûëÏ†êÍ≥º ÎÅùÏ†ê ÏÇ¨Ïù¥)
		FVector AdjustedLocation = FMath::Lerp(StartVector, EndVector, EffectLocationAlpha);
		// Ïù¥ÌéôÌä∏ Ïä§Ìè∞
		NiagaraComponent = UNiagaraFunctionLibrary::SpawnSystemAtLocation(GetWorld(), Fx, AdjustedLocation,	DashRotation);
		if (NiagaraComponent)
		{
			float DashLengh = FVector::DistXY(StartVector, EndVector);
			float DefaultFxLength = 100.0f;
			//Î™©Ìëú Í±∞Î¶¨ÏôÄ ÌëúÏ§Ä Ïù¥ÌéôÌä∏ Í∏∏Ïù¥Î•º ÎπÑÍµêÌïòÏó¨ Ïù¥ÌéôÌä∏ ÌÅ¨Í∏∞ ÏÑ§Ï†ï
			float FxScaleX = DashLengh / DefaultFxLength;
			FVector DashScale(FxScaleX * FxScaleMultiplier.X, FxScaleMultiplier.Y, FxScaleMultiplier.Z);
			NiagaraComponent->SetVariableVec3(FName("MeshScale"), DashScale);
		}
	}
}
